package com.powerbench.ui.notification;

import android.util.SparseArray;

import com.powerbench.R;
import com.powerbench.constants.UIConstants;

/**
 * The class used that contains the cache of notification drawables.
 */
public class NotificationDrawableCache {

    /**
     * The cache of power drawables.
     */
    private SparseArray<Integer> mPowerCache = new SparseArray<Integer>();

    /**
     * The cache of current drawables.
     */
    private SparseArray<Integer> mCurrentCache = new SparseArray<Integer>();

    /**
     * The cache of battery life drawables.
     */
    private SparseArray<Integer> mBatteryLifeCache = new SparseArray<Integer>();

    public NotificationDrawableCache() {
        initialize();
    }

    /**
     * Initialize the values for this generator.
     */
    private void initialize() {
        mPowerCache.put(100, R.drawable.notification_power_100);
        mPowerCache.put(110, R.drawable.notification_power_110);
        mPowerCache.put(120, R.drawable.notification_power_120);
        mPowerCache.put(130, R.drawable.notification_power_130);
        mPowerCache.put(140, R.drawable.notification_power_140);
        mPowerCache.put(150, R.drawable.notification_power_150);
        mPowerCache.put(160, R.drawable.notification_power_160);
        mPowerCache.put(170, R.drawable.notification_power_170);
        mPowerCache.put(180, R.drawable.notification_power_180);
        mPowerCache.put(190, R.drawable.notification_power_190);
        mPowerCache.put(200, R.drawable.notification_power_200);
        mPowerCache.put(210, R.drawable.notification_power_210);
        mPowerCache.put(220, R.drawable.notification_power_220);
        mPowerCache.put(230, R.drawable.notification_power_230);
        mPowerCache.put(240, R.drawable.notification_power_240);
        mPowerCache.put(250, R.drawable.notification_power_250);
        mPowerCache.put(260, R.drawable.notification_power_260);
        mPowerCache.put(270, R.drawable.notification_power_270);
        mPowerCache.put(280, R.drawable.notification_power_280);
        mPowerCache.put(290, R.drawable.notification_power_290);
        mPowerCache.put(300, R.drawable.notification_power_300);
        mPowerCache.put(310, R.drawable.notification_power_310);
        mPowerCache.put(320, R.drawable.notification_power_320);
        mPowerCache.put(330, R.drawable.notification_power_330);
        mPowerCache.put(340, R.drawable.notification_power_340);
        mPowerCache.put(350, R.drawable.notification_power_350);
        mPowerCache.put(360, R.drawable.notification_power_360);
        mPowerCache.put(370, R.drawable.notification_power_370);
        mPowerCache.put(380, R.drawable.notification_power_380);
        mPowerCache.put(390, R.drawable.notification_power_390);
        mPowerCache.put(400, R.drawable.notification_power_400);
        mPowerCache.put(410, R.drawable.notification_power_410);
        mPowerCache.put(420, R.drawable.notification_power_420);
        mPowerCache.put(430, R.drawable.notification_power_430);
        mPowerCache.put(440, R.drawable.notification_power_440);
        mPowerCache.put(450, R.drawable.notification_power_450);
        mPowerCache.put(460, R.drawable.notification_power_460);
        mPowerCache.put(470, R.drawable.notification_power_470);
        mPowerCache.put(480, R.drawable.notification_power_480);
        mPowerCache.put(490, R.drawable.notification_power_490);
        mPowerCache.put(500, R.drawable.notification_power_500);
        mPowerCache.put(510, R.drawable.notification_power_510);
        mPowerCache.put(520, R.drawable.notification_power_520);
        mPowerCache.put(530, R.drawable.notification_power_530);
        mPowerCache.put(540, R.drawable.notification_power_540);
        mPowerCache.put(550, R.drawable.notification_power_550);
        mPowerCache.put(560, R.drawable.notification_power_560);
        mPowerCache.put(570, R.drawable.notification_power_570);
        mPowerCache.put(580, R.drawable.notification_power_580);
        mPowerCache.put(590, R.drawable.notification_power_590);
        mPowerCache.put(600, R.drawable.notification_power_600);
        mPowerCache.put(610, R.drawable.notification_power_610);
        mPowerCache.put(620, R.drawable.notification_power_620);
        mPowerCache.put(630, R.drawable.notification_power_630);
        mPowerCache.put(640, R.drawable.notification_power_640);
        mPowerCache.put(650, R.drawable.notification_power_650);
        mPowerCache.put(660, R.drawable.notification_power_660);
        mPowerCache.put(670, R.drawable.notification_power_670);
        mPowerCache.put(680, R.drawable.notification_power_680);
        mPowerCache.put(690, R.drawable.notification_power_690);
        mPowerCache.put(700, R.drawable.notification_power_700);
        mPowerCache.put(710, R.drawable.notification_power_710);
        mPowerCache.put(720, R.drawable.notification_power_720);
        mPowerCache.put(730, R.drawable.notification_power_730);
        mPowerCache.put(740, R.drawable.notification_power_740);
        mPowerCache.put(750, R.drawable.notification_power_750);
        mPowerCache.put(760, R.drawable.notification_power_760);
        mPowerCache.put(770, R.drawable.notification_power_770);
        mPowerCache.put(780, R.drawable.notification_power_780);
        mPowerCache.put(790, R.drawable.notification_power_790);
        mPowerCache.put(800, R.drawable.notification_power_800);
        mPowerCache.put(810, R.drawable.notification_power_810);
        mPowerCache.put(820, R.drawable.notification_power_820);
        mPowerCache.put(830, R.drawable.notification_power_830);
        mPowerCache.put(840, R.drawable.notification_power_840);
        mPowerCache.put(850, R.drawable.notification_power_850);
        mPowerCache.put(860, R.drawable.notification_power_860);
        mPowerCache.put(870, R.drawable.notification_power_870);
        mPowerCache.put(880, R.drawable.notification_power_880);
        mPowerCache.put(890, R.drawable.notification_power_890);
        mPowerCache.put(900, R.drawable.notification_power_900);
        mPowerCache.put(910, R.drawable.notification_power_910);
        mPowerCache.put(920, R.drawable.notification_power_920);
        mPowerCache.put(930, R.drawable.notification_power_930);
        mPowerCache.put(940, R.drawable.notification_power_940);
        mPowerCache.put(950, R.drawable.notification_power_950);
        mPowerCache.put(960, R.drawable.notification_power_960);
        mPowerCache.put(970, R.drawable.notification_power_970);
        mPowerCache.put(980, R.drawable.notification_power_980);
        mPowerCache.put(990, R.drawable.notification_power_990);
        mPowerCache.put(1000, R.drawable.notification_power_1000);
        mPowerCache.put(1100, R.drawable.notification_power_1100);
        mPowerCache.put(1200, R.drawable.notification_power_1200);
        mPowerCache.put(1300, R.drawable.notification_power_1300);
        mPowerCache.put(1400, R.drawable.notification_power_1400);
        mPowerCache.put(1500, R.drawable.notification_power_1500);
        mPowerCache.put(1600, R.drawable.notification_power_1600);
        mPowerCache.put(1700, R.drawable.notification_power_1700);
        mPowerCache.put(1800, R.drawable.notification_power_1800);
        mPowerCache.put(1900, R.drawable.notification_power_1900);
        mPowerCache.put(2000, R.drawable.notification_power_2000);
        mPowerCache.put(2100, R.drawable.notification_power_2100);
        mPowerCache.put(2200, R.drawable.notification_power_2200);
        mPowerCache.put(2300, R.drawable.notification_power_2300);
        mPowerCache.put(2400, R.drawable.notification_power_2400);
        mPowerCache.put(2500, R.drawable.notification_power_2500);
        mPowerCache.put(2600, R.drawable.notification_power_2600);
        mPowerCache.put(2700, R.drawable.notification_power_2700);
        mPowerCache.put(2800, R.drawable.notification_power_2800);
        mPowerCache.put(2900, R.drawable.notification_power_2900);
        mPowerCache.put(3000, R.drawable.notification_power_3000);
        mPowerCache.put(3100, R.drawable.notification_power_3100);
        mPowerCache.put(3200, R.drawable.notification_power_3200);
        mPowerCache.put(3300, R.drawable.notification_power_3300);
        mPowerCache.put(3400, R.drawable.notification_power_3400);
        mPowerCache.put(3500, R.drawable.notification_power_3500);
        mPowerCache.put(3600, R.drawable.notification_power_3600);
        mPowerCache.put(3700, R.drawable.notification_power_3700);
        mPowerCache.put(3800, R.drawable.notification_power_3800);
        mPowerCache.put(3900, R.drawable.notification_power_3900);
        mPowerCache.put(4000, R.drawable.notification_power_4000);
        mPowerCache.put(4100, R.drawable.notification_power_4100);
        mPowerCache.put(4200, R.drawable.notification_power_4200);
        mPowerCache.put(4300, R.drawable.notification_power_4300);
        mPowerCache.put(4400, R.drawable.notification_power_4400);
        mPowerCache.put(4500, R.drawable.notification_power_4500);
        mPowerCache.put(4600, R.drawable.notification_power_4600);
        mPowerCache.put(4700, R.drawable.notification_power_4700);
        mPowerCache.put(4800, R.drawable.notification_power_4800);
        mPowerCache.put(4900, R.drawable.notification_power_4900);
        mPowerCache.put(5000, R.drawable.notification_power_5000);
        mPowerCache.put(5100, R.drawable.notification_power_5100);
        mPowerCache.put(5200, R.drawable.notification_power_5200);
        mPowerCache.put(5300, R.drawable.notification_power_5300);
        mPowerCache.put(5400, R.drawable.notification_power_5400);
        mPowerCache.put(5500, R.drawable.notification_power_5500);
        mPowerCache.put(5600, R.drawable.notification_power_5600);
        mPowerCache.put(5700, R.drawable.notification_power_5700);
        mPowerCache.put(5800, R.drawable.notification_power_5800);
        mPowerCache.put(5900, R.drawable.notification_power_5900);
        mPowerCache.put(6000, R.drawable.notification_power_6000);
        mPowerCache.put(6100, R.drawable.notification_power_6100);
        mPowerCache.put(6200, R.drawable.notification_power_6200);
        mPowerCache.put(6300, R.drawable.notification_power_6300);
        mPowerCache.put(6400, R.drawable.notification_power_6400);
        mPowerCache.put(6500, R.drawable.notification_power_6500);
        mPowerCache.put(6600, R.drawable.notification_power_6600);
        mPowerCache.put(6700, R.drawable.notification_power_6700);
        mPowerCache.put(6800, R.drawable.notification_power_6800);
        mPowerCache.put(6900, R.drawable.notification_power_6900);
        mPowerCache.put(7000, R.drawable.notification_power_7000);
        mPowerCache.put(7100, R.drawable.notification_power_7100);
        mPowerCache.put(7200, R.drawable.notification_power_7200);
        mPowerCache.put(7300, R.drawable.notification_power_7300);
        mPowerCache.put(7400, R.drawable.notification_power_7400);
        mPowerCache.put(7500, R.drawable.notification_power_7500);
        mPowerCache.put(7600, R.drawable.notification_power_7600);
        mPowerCache.put(7700, R.drawable.notification_power_7700);
        mPowerCache.put(7800, R.drawable.notification_power_7800);
        mPowerCache.put(7900, R.drawable.notification_power_7900);
        mPowerCache.put(8000, R.drawable.notification_power_8000);
        mPowerCache.put(8100, R.drawable.notification_power_8100);
        mPowerCache.put(8200, R.drawable.notification_power_8200);
        mPowerCache.put(8300, R.drawable.notification_power_8300);
        mPowerCache.put(8400, R.drawable.notification_power_8400);
        mPowerCache.put(8500, R.drawable.notification_power_8500);
        mPowerCache.put(8600, R.drawable.notification_power_8600);
        mPowerCache.put(8700, R.drawable.notification_power_8700);
        mPowerCache.put(8800, R.drawable.notification_power_8800);
        mPowerCache.put(8900, R.drawable.notification_power_8900);
        mPowerCache.put(9000, R.drawable.notification_power_9000);
        mPowerCache.put(9100, R.drawable.notification_power_9100);
        mPowerCache.put(9200, R.drawable.notification_power_9200);
        mPowerCache.put(9300, R.drawable.notification_power_9300);
        mPowerCache.put(9400, R.drawable.notification_power_9400);
        mPowerCache.put(9500, R.drawable.notification_power_9500);
        mPowerCache.put(9600, R.drawable.notification_power_9600);
        mPowerCache.put(9700, R.drawable.notification_power_9700);
        mPowerCache.put(9800, R.drawable.notification_power_9800);
        mPowerCache.put(9900, R.drawable.notification_power_9900);
        mPowerCache.put(10000, R.drawable.notification_power_10000);
        mPowerCache.put(11000, R.drawable.notification_power_11000);
        mPowerCache.put(12000, R.drawable.notification_power_12000);
        mPowerCache.put(13000, R.drawable.notification_power_13000);
        mPowerCache.put(14000, R.drawable.notification_power_14000);
        mPowerCache.put(15000, R.drawable.notification_power_15000);
        mPowerCache.put(16000, R.drawable.notification_power_16000);
        mPowerCache.put(17000, R.drawable.notification_power_17000);
        mPowerCache.put(18000, R.drawable.notification_power_18000);
        mPowerCache.put(19000, R.drawable.notification_power_19000);
        mCurrentCache.put(100, R.drawable.notification_current_100);
        mCurrentCache.put(110, R.drawable.notification_current_110);
        mCurrentCache.put(120, R.drawable.notification_current_120);
        mCurrentCache.put(130, R.drawable.notification_current_130);
        mCurrentCache.put(140, R.drawable.notification_current_140);
        mCurrentCache.put(150, R.drawable.notification_current_150);
        mCurrentCache.put(160, R.drawable.notification_current_160);
        mCurrentCache.put(170, R.drawable.notification_current_170);
        mCurrentCache.put(180, R.drawable.notification_current_180);
        mCurrentCache.put(190, R.drawable.notification_current_190);
        mCurrentCache.put(200, R.drawable.notification_current_200);
        mCurrentCache.put(210, R.drawable.notification_current_210);
        mCurrentCache.put(220, R.drawable.notification_current_220);
        mCurrentCache.put(230, R.drawable.notification_current_230);
        mCurrentCache.put(240, R.drawable.notification_current_240);
        mCurrentCache.put(250, R.drawable.notification_current_250);
        mCurrentCache.put(260, R.drawable.notification_current_260);
        mCurrentCache.put(270, R.drawable.notification_current_270);
        mCurrentCache.put(280, R.drawable.notification_current_280);
        mCurrentCache.put(290, R.drawable.notification_current_290);
        mCurrentCache.put(300, R.drawable.notification_current_300);
        mCurrentCache.put(310, R.drawable.notification_current_310);
        mCurrentCache.put(320, R.drawable.notification_current_320);
        mCurrentCache.put(330, R.drawable.notification_current_330);
        mCurrentCache.put(340, R.drawable.notification_current_340);
        mCurrentCache.put(350, R.drawable.notification_current_350);
        mCurrentCache.put(360, R.drawable.notification_current_360);
        mCurrentCache.put(370, R.drawable.notification_current_370);
        mCurrentCache.put(380, R.drawable.notification_current_380);
        mCurrentCache.put(390, R.drawable.notification_current_390);
        mCurrentCache.put(400, R.drawable.notification_current_400);
        mCurrentCache.put(410, R.drawable.notification_current_410);
        mCurrentCache.put(420, R.drawable.notification_current_420);
        mCurrentCache.put(430, R.drawable.notification_current_430);
        mCurrentCache.put(440, R.drawable.notification_current_440);
        mCurrentCache.put(450, R.drawable.notification_current_450);
        mCurrentCache.put(460, R.drawable.notification_current_460);
        mCurrentCache.put(470, R.drawable.notification_current_470);
        mCurrentCache.put(480, R.drawable.notification_current_480);
        mCurrentCache.put(490, R.drawable.notification_current_490);
        mCurrentCache.put(500, R.drawable.notification_current_500);
        mCurrentCache.put(510, R.drawable.notification_current_510);
        mCurrentCache.put(520, R.drawable.notification_current_520);
        mCurrentCache.put(530, R.drawable.notification_current_530);
        mCurrentCache.put(540, R.drawable.notification_current_540);
        mCurrentCache.put(550, R.drawable.notification_current_550);
        mCurrentCache.put(560, R.drawable.notification_current_560);
        mCurrentCache.put(570, R.drawable.notification_current_570);
        mCurrentCache.put(580, R.drawable.notification_current_580);
        mCurrentCache.put(590, R.drawable.notification_current_590);
        mCurrentCache.put(600, R.drawable.notification_current_600);
        mCurrentCache.put(610, R.drawable.notification_current_610);
        mCurrentCache.put(620, R.drawable.notification_current_620);
        mCurrentCache.put(630, R.drawable.notification_current_630);
        mCurrentCache.put(640, R.drawable.notification_current_640);
        mCurrentCache.put(650, R.drawable.notification_current_650);
        mCurrentCache.put(660, R.drawable.notification_current_660);
        mCurrentCache.put(670, R.drawable.notification_current_670);
        mCurrentCache.put(680, R.drawable.notification_current_680);
        mCurrentCache.put(690, R.drawable.notification_current_690);
        mCurrentCache.put(700, R.drawable.notification_current_700);
        mCurrentCache.put(710, R.drawable.notification_current_710);
        mCurrentCache.put(720, R.drawable.notification_current_720);
        mCurrentCache.put(730, R.drawable.notification_current_730);
        mCurrentCache.put(740, R.drawable.notification_current_740);
        mCurrentCache.put(750, R.drawable.notification_current_750);
        mCurrentCache.put(760, R.drawable.notification_current_760);
        mCurrentCache.put(770, R.drawable.notification_current_770);
        mCurrentCache.put(780, R.drawable.notification_current_780);
        mCurrentCache.put(790, R.drawable.notification_current_790);
        mCurrentCache.put(800, R.drawable.notification_current_800);
        mCurrentCache.put(810, R.drawable.notification_current_810);
        mCurrentCache.put(820, R.drawable.notification_current_820);
        mCurrentCache.put(830, R.drawable.notification_current_830);
        mCurrentCache.put(840, R.drawable.notification_current_840);
        mCurrentCache.put(850, R.drawable.notification_current_850);
        mCurrentCache.put(860, R.drawable.notification_current_860);
        mCurrentCache.put(870, R.drawable.notification_current_870);
        mCurrentCache.put(880, R.drawable.notification_current_880);
        mCurrentCache.put(890, R.drawable.notification_current_890);
        mCurrentCache.put(900, R.drawable.notification_current_900);
        mCurrentCache.put(910, R.drawable.notification_current_910);
        mCurrentCache.put(920, R.drawable.notification_current_920);
        mCurrentCache.put(930, R.drawable.notification_current_930);
        mCurrentCache.put(940, R.drawable.notification_current_940);
        mCurrentCache.put(950, R.drawable.notification_current_950);
        mCurrentCache.put(960, R.drawable.notification_current_960);
        mCurrentCache.put(970, R.drawable.notification_current_970);
        mCurrentCache.put(980, R.drawable.notification_current_980);
        mCurrentCache.put(990, R.drawable.notification_current_990);
        mCurrentCache.put(1000, R.drawable.notification_current_1000);
        mCurrentCache.put(1100, R.drawable.notification_current_1100);
        mCurrentCache.put(1200, R.drawable.notification_current_1200);
        mCurrentCache.put(1300, R.drawable.notification_current_1300);
        mCurrentCache.put(1400, R.drawable.notification_current_1400);
        mCurrentCache.put(1500, R.drawable.notification_current_1500);
        mCurrentCache.put(1600, R.drawable.notification_current_1600);
        mCurrentCache.put(1700, R.drawable.notification_current_1700);
        mCurrentCache.put(1800, R.drawable.notification_current_1800);
        mCurrentCache.put(1900, R.drawable.notification_current_1900);
        mCurrentCache.put(2000, R.drawable.notification_current_2000);
        mCurrentCache.put(2100, R.drawable.notification_current_2100);
        mCurrentCache.put(2200, R.drawable.notification_current_2200);
        mCurrentCache.put(2300, R.drawable.notification_current_2300);
        mCurrentCache.put(2400, R.drawable.notification_current_2400);
        mCurrentCache.put(2500, R.drawable.notification_current_2500);
        mCurrentCache.put(2600, R.drawable.notification_current_2600);
        mCurrentCache.put(2700, R.drawable.notification_current_2700);
        mCurrentCache.put(2800, R.drawable.notification_current_2800);
        mCurrentCache.put(2900, R.drawable.notification_current_2900);
        mCurrentCache.put(3000, R.drawable.notification_current_3000);
        mCurrentCache.put(3100, R.drawable.notification_current_3100);
        mCurrentCache.put(3200, R.drawable.notification_current_3200);
        mCurrentCache.put(3300, R.drawable.notification_current_3300);
        mCurrentCache.put(3400, R.drawable.notification_current_3400);
        mCurrentCache.put(3500, R.drawable.notification_current_3500);
        mCurrentCache.put(3600, R.drawable.notification_current_3600);
        mCurrentCache.put(3700, R.drawable.notification_current_3700);
        mCurrentCache.put(3800, R.drawable.notification_current_3800);
        mCurrentCache.put(3900, R.drawable.notification_current_3900);
        mCurrentCache.put(4000, R.drawable.notification_current_4000);
        mCurrentCache.put(4100, R.drawable.notification_current_4100);
        mCurrentCache.put(4200, R.drawable.notification_current_4200);
        mCurrentCache.put(4300, R.drawable.notification_current_4300);
        mCurrentCache.put(4400, R.drawable.notification_current_4400);
        mCurrentCache.put(4500, R.drawable.notification_current_4500);
        mCurrentCache.put(4600, R.drawable.notification_current_4600);
        mCurrentCache.put(4700, R.drawable.notification_current_4700);
        mCurrentCache.put(4800, R.drawable.notification_current_4800);
        mCurrentCache.put(4900, R.drawable.notification_current_4900);
        mCurrentCache.put(5000, R.drawable.notification_current_5000);
        mCurrentCache.put(5100, R.drawable.notification_current_5100);
        mCurrentCache.put(5200, R.drawable.notification_current_5200);
        mCurrentCache.put(5300, R.drawable.notification_current_5300);
        mCurrentCache.put(5400, R.drawable.notification_current_5400);
        mCurrentCache.put(5500, R.drawable.notification_current_5500);
        mCurrentCache.put(5600, R.drawable.notification_current_5600);
        mCurrentCache.put(5700, R.drawable.notification_current_5700);
        mCurrentCache.put(5800, R.drawable.notification_current_5800);
        mCurrentCache.put(5900, R.drawable.notification_current_5900);
        mCurrentCache.put(6000, R.drawable.notification_current_6000);
        mCurrentCache.put(6100, R.drawable.notification_current_6100);
        mCurrentCache.put(6200, R.drawable.notification_current_6200);
        mCurrentCache.put(6300, R.drawable.notification_current_6300);
        mCurrentCache.put(6400, R.drawable.notification_current_6400);
        mCurrentCache.put(6500, R.drawable.notification_current_6500);
        mCurrentCache.put(6600, R.drawable.notification_current_6600);
        mCurrentCache.put(6700, R.drawable.notification_current_6700);
        mCurrentCache.put(6800, R.drawable.notification_current_6800);
        mCurrentCache.put(6900, R.drawable.notification_current_6900);
        mCurrentCache.put(7000, R.drawable.notification_current_7000);
        mCurrentCache.put(7100, R.drawable.notification_current_7100);
        mCurrentCache.put(7200, R.drawable.notification_current_7200);
        mCurrentCache.put(7300, R.drawable.notification_current_7300);
        mCurrentCache.put(7400, R.drawable.notification_current_7400);
        mCurrentCache.put(7500, R.drawable.notification_current_7500);
        mCurrentCache.put(7600, R.drawable.notification_current_7600);
        mCurrentCache.put(7700, R.drawable.notification_current_7700);
        mCurrentCache.put(7800, R.drawable.notification_current_7800);
        mCurrentCache.put(7900, R.drawable.notification_current_7900);
        mCurrentCache.put(8000, R.drawable.notification_current_8000);
        mCurrentCache.put(8100, R.drawable.notification_current_8100);
        mCurrentCache.put(8200, R.drawable.notification_current_8200);
        mCurrentCache.put(8300, R.drawable.notification_current_8300);
        mCurrentCache.put(8400, R.drawable.notification_current_8400);
        mCurrentCache.put(8500, R.drawable.notification_current_8500);
        mCurrentCache.put(8600, R.drawable.notification_current_8600);
        mCurrentCache.put(8700, R.drawable.notification_current_8700);
        mCurrentCache.put(8800, R.drawable.notification_current_8800);
        mCurrentCache.put(8900, R.drawable.notification_current_8900);
        mCurrentCache.put(9000, R.drawable.notification_current_9000);
        mCurrentCache.put(9100, R.drawable.notification_current_9100);
        mCurrentCache.put(9200, R.drawable.notification_current_9200);
        mCurrentCache.put(9300, R.drawable.notification_current_9300);
        mCurrentCache.put(9400, R.drawable.notification_current_9400);
        mCurrentCache.put(9500, R.drawable.notification_current_9500);
        mCurrentCache.put(9600, R.drawable.notification_current_9600);
        mCurrentCache.put(9700, R.drawable.notification_current_9700);
        mCurrentCache.put(9800, R.drawable.notification_current_9800);
        mCurrentCache.put(9900, R.drawable.notification_current_9900);
        mBatteryLifeCache.put(1, R.drawable.notification_battery_life_1);
        mBatteryLifeCache.put(2, R.drawable.notification_battery_life_2);
        mBatteryLifeCache.put(3, R.drawable.notification_battery_life_3);
        mBatteryLifeCache.put(4, R.drawable.notification_battery_life_4);
        mBatteryLifeCache.put(5, R.drawable.notification_battery_life_5);
        mBatteryLifeCache.put(6, R.drawable.notification_battery_life_6);
        mBatteryLifeCache.put(7, R.drawable.notification_battery_life_7);
        mBatteryLifeCache.put(8, R.drawable.notification_battery_life_8);
        mBatteryLifeCache.put(9, R.drawable.notification_battery_life_9);
        mBatteryLifeCache.put(10, R.drawable.notification_battery_life_10);
        mBatteryLifeCache.put(11, R.drawable.notification_battery_life_11);
        mBatteryLifeCache.put(12, R.drawable.notification_battery_life_12);
        mBatteryLifeCache.put(13, R.drawable.notification_battery_life_13);
        mBatteryLifeCache.put(14, R.drawable.notification_battery_life_14);
        mBatteryLifeCache.put(15, R.drawable.notification_battery_life_15);
        mBatteryLifeCache.put(16, R.drawable.notification_battery_life_16);
        mBatteryLifeCache.put(17, R.drawable.notification_battery_life_17);
        mBatteryLifeCache.put(18, R.drawable.notification_battery_life_18);
        mBatteryLifeCache.put(19, R.drawable.notification_battery_life_19);
        mBatteryLifeCache.put(20, R.drawable.notification_battery_life_20);
        mBatteryLifeCache.put(21, R.drawable.notification_battery_life_21);
        mBatteryLifeCache.put(22, R.drawable.notification_battery_life_22);
        mBatteryLifeCache.put(23, R.drawable.notification_battery_life_23);
        mBatteryLifeCache.put(24, R.drawable.notification_battery_life_24);
        mBatteryLifeCache.put(25, R.drawable.notification_battery_life_25);
        mBatteryLifeCache.put(26, R.drawable.notification_battery_life_26);
        mBatteryLifeCache.put(27, R.drawable.notification_battery_life_27);
        mBatteryLifeCache.put(28, R.drawable.notification_battery_life_28);
        mBatteryLifeCache.put(29, R.drawable.notification_battery_life_29);
        mBatteryLifeCache.put(30, R.drawable.notification_battery_life_30);
        mBatteryLifeCache.put(31, R.drawable.notification_battery_life_31);
        mBatteryLifeCache.put(32, R.drawable.notification_battery_life_32);
        mBatteryLifeCache.put(33, R.drawable.notification_battery_life_33);
        mBatteryLifeCache.put(34, R.drawable.notification_battery_life_34);
        mBatteryLifeCache.put(35, R.drawable.notification_battery_life_35);
        mBatteryLifeCache.put(36, R.drawable.notification_battery_life_36);
        mBatteryLifeCache.put(37, R.drawable.notification_battery_life_37);
        mBatteryLifeCache.put(38, R.drawable.notification_battery_life_38);
        mBatteryLifeCache.put(39, R.drawable.notification_battery_life_39);
        mBatteryLifeCache.put(40, R.drawable.notification_battery_life_40);
        mBatteryLifeCache.put(41, R.drawable.notification_battery_life_41);
        mBatteryLifeCache.put(42, R.drawable.notification_battery_life_42);
        mBatteryLifeCache.put(43, R.drawable.notification_battery_life_43);
        mBatteryLifeCache.put(44, R.drawable.notification_battery_life_44);
        mBatteryLifeCache.put(45, R.drawable.notification_battery_life_45);
        mBatteryLifeCache.put(46, R.drawable.notification_battery_life_46);
        mBatteryLifeCache.put(47, R.drawable.notification_battery_life_47);
        mBatteryLifeCache.put(48, R.drawable.notification_battery_life_48);
        mBatteryLifeCache.put(49, R.drawable.notification_battery_life_49);
        mBatteryLifeCache.put(50, R.drawable.notification_battery_life_50);
        mBatteryLifeCache.put(51, R.drawable.notification_battery_life_51);
        mBatteryLifeCache.put(52, R.drawable.notification_battery_life_52);
        mBatteryLifeCache.put(53, R.drawable.notification_battery_life_53);
        mBatteryLifeCache.put(54, R.drawable.notification_battery_life_54);
        mBatteryLifeCache.put(55, R.drawable.notification_battery_life_55);
        mBatteryLifeCache.put(56, R.drawable.notification_battery_life_56);
        mBatteryLifeCache.put(57, R.drawable.notification_battery_life_57);
        mBatteryLifeCache.put(58, R.drawable.notification_battery_life_58);
        mBatteryLifeCache.put(59, R.drawable.notification_battery_life_59);
        mBatteryLifeCache.put(60, R.drawable.notification_battery_life_60);
        mBatteryLifeCache.put(61, R.drawable.notification_battery_life_61);
        mBatteryLifeCache.put(62, R.drawable.notification_battery_life_62);
        mBatteryLifeCache.put(63, R.drawable.notification_battery_life_63);
        mBatteryLifeCache.put(64, R.drawable.notification_battery_life_64);
        mBatteryLifeCache.put(65, R.drawable.notification_battery_life_65);
        mBatteryLifeCache.put(66, R.drawable.notification_battery_life_66);
        mBatteryLifeCache.put(67, R.drawable.notification_battery_life_67);
        mBatteryLifeCache.put(68, R.drawable.notification_battery_life_68);
        mBatteryLifeCache.put(69, R.drawable.notification_battery_life_69);
        mBatteryLifeCache.put(70, R.drawable.notification_battery_life_70);
        mBatteryLifeCache.put(71, R.drawable.notification_battery_life_71);
        mBatteryLifeCache.put(72, R.drawable.notification_battery_life_72);
        mBatteryLifeCache.put(73, R.drawable.notification_battery_life_73);
        mBatteryLifeCache.put(74, R.drawable.notification_battery_life_74);
        mBatteryLifeCache.put(75, R.drawable.notification_battery_life_75);
        mBatteryLifeCache.put(76, R.drawable.notification_battery_life_76);
        mBatteryLifeCache.put(77, R.drawable.notification_battery_life_77);
        mBatteryLifeCache.put(78, R.drawable.notification_battery_life_78);
        mBatteryLifeCache.put(79, R.drawable.notification_battery_life_79);
        mBatteryLifeCache.put(80, R.drawable.notification_battery_life_80);
        mBatteryLifeCache.put(81, R.drawable.notification_battery_life_81);
        mBatteryLifeCache.put(82, R.drawable.notification_battery_life_82);
        mBatteryLifeCache.put(83, R.drawable.notification_battery_life_83);
        mBatteryLifeCache.put(84, R.drawable.notification_battery_life_84);
        mBatteryLifeCache.put(85, R.drawable.notification_battery_life_85);
        mBatteryLifeCache.put(86, R.drawable.notification_battery_life_86);
        mBatteryLifeCache.put(87, R.drawable.notification_battery_life_87);
        mBatteryLifeCache.put(88, R.drawable.notification_battery_life_88);
        mBatteryLifeCache.put(89, R.drawable.notification_battery_life_89);
        mBatteryLifeCache.put(90, R.drawable.notification_battery_life_90);
        mBatteryLifeCache.put(91, R.drawable.notification_battery_life_91);
        mBatteryLifeCache.put(92, R.drawable.notification_battery_life_92);
        mBatteryLifeCache.put(93, R.drawable.notification_battery_life_93);
        mBatteryLifeCache.put(94, R.drawable.notification_battery_life_94);
        mBatteryLifeCache.put(95, R.drawable.notification_battery_life_95);
        mBatteryLifeCache.put(96, R.drawable.notification_battery_life_96);
        mBatteryLifeCache.put(97, R.drawable.notification_battery_life_97);
        mBatteryLifeCache.put(98, R.drawable.notification_battery_life_98);
        mBatteryLifeCache.put(99, R.drawable.notification_battery_life_99);
        mBatteryLifeCache.put(100, R.drawable.notification_battery_life_100);
        mBatteryLifeCache.put(101, R.drawable.notification_battery_life_101);
        mBatteryLifeCache.put(102, R.drawable.notification_battery_life_102);
        mBatteryLifeCache.put(103, R.drawable.notification_battery_life_103);
        mBatteryLifeCache.put(104, R.drawable.notification_battery_life_104);
        mBatteryLifeCache.put(105, R.drawable.notification_battery_life_105);
        mBatteryLifeCache.put(106, R.drawable.notification_battery_life_106);
        mBatteryLifeCache.put(107, R.drawable.notification_battery_life_107);
        mBatteryLifeCache.put(108, R.drawable.notification_battery_life_108);
        mBatteryLifeCache.put(109, R.drawable.notification_battery_life_109);
        mBatteryLifeCache.put(110, R.drawable.notification_battery_life_110);
        mBatteryLifeCache.put(111, R.drawable.notification_battery_life_111);
        mBatteryLifeCache.put(112, R.drawable.notification_battery_life_112);
        mBatteryLifeCache.put(113, R.drawable.notification_battery_life_113);
        mBatteryLifeCache.put(114, R.drawable.notification_battery_life_114);
        mBatteryLifeCache.put(115, R.drawable.notification_battery_life_115);
        mBatteryLifeCache.put(116, R.drawable.notification_battery_life_116);
        mBatteryLifeCache.put(117, R.drawable.notification_battery_life_117);
        mBatteryLifeCache.put(118, R.drawable.notification_battery_life_118);
        mBatteryLifeCache.put(119, R.drawable.notification_battery_life_119);
        mBatteryLifeCache.put(120, R.drawable.notification_battery_life_120);
        mBatteryLifeCache.put(121, R.drawable.notification_battery_life_121);
        mBatteryLifeCache.put(122, R.drawable.notification_battery_life_122);
        mBatteryLifeCache.put(123, R.drawable.notification_battery_life_123);
        mBatteryLifeCache.put(124, R.drawable.notification_battery_life_124);
        mBatteryLifeCache.put(125, R.drawable.notification_battery_life_125);
        mBatteryLifeCache.put(126, R.drawable.notification_battery_life_126);
        mBatteryLifeCache.put(127, R.drawable.notification_battery_life_127);
        mBatteryLifeCache.put(128, R.drawable.notification_battery_life_128);
        mBatteryLifeCache.put(129, R.drawable.notification_battery_life_129);
        mBatteryLifeCache.put(130, R.drawable.notification_battery_life_130);
        mBatteryLifeCache.put(131, R.drawable.notification_battery_life_131);
        mBatteryLifeCache.put(132, R.drawable.notification_battery_life_132);
        mBatteryLifeCache.put(133, R.drawable.notification_battery_life_133);
        mBatteryLifeCache.put(134, R.drawable.notification_battery_life_134);
        mBatteryLifeCache.put(135, R.drawable.notification_battery_life_135);
        mBatteryLifeCache.put(136, R.drawable.notification_battery_life_136);
        mBatteryLifeCache.put(137, R.drawable.notification_battery_life_137);
        mBatteryLifeCache.put(138, R.drawable.notification_battery_life_138);
        mBatteryLifeCache.put(139, R.drawable.notification_battery_life_139);
        mBatteryLifeCache.put(140, R.drawable.notification_battery_life_140);
        mBatteryLifeCache.put(141, R.drawable.notification_battery_life_141);
        mBatteryLifeCache.put(142, R.drawable.notification_battery_life_142);
        mBatteryLifeCache.put(143, R.drawable.notification_battery_life_143);
        mBatteryLifeCache.put(144, R.drawable.notification_battery_life_144);
        mBatteryLifeCache.put(145, R.drawable.notification_battery_life_145);
        mBatteryLifeCache.put(146, R.drawable.notification_battery_life_146);
        mBatteryLifeCache.put(147, R.drawable.notification_battery_life_147);
        mBatteryLifeCache.put(148, R.drawable.notification_battery_life_148);
        mBatteryLifeCache.put(149, R.drawable.notification_battery_life_149);
        mBatteryLifeCache.put(150, R.drawable.notification_battery_life_150);
        mBatteryLifeCache.put(151, R.drawable.notification_battery_life_151);
        mBatteryLifeCache.put(152, R.drawable.notification_battery_life_152);
        mBatteryLifeCache.put(153, R.drawable.notification_battery_life_153);
        mBatteryLifeCache.put(154, R.drawable.notification_battery_life_154);
        mBatteryLifeCache.put(155, R.drawable.notification_battery_life_155);
        mBatteryLifeCache.put(156, R.drawable.notification_battery_life_156);
        mBatteryLifeCache.put(157, R.drawable.notification_battery_life_157);
        mBatteryLifeCache.put(158, R.drawable.notification_battery_life_158);
        mBatteryLifeCache.put(159, R.drawable.notification_battery_life_159);
        mBatteryLifeCache.put(160, R.drawable.notification_battery_life_160);
        mBatteryLifeCache.put(161, R.drawable.notification_battery_life_161);
        mBatteryLifeCache.put(162, R.drawable.notification_battery_life_162);
        mBatteryLifeCache.put(163, R.drawable.notification_battery_life_163);
        mBatteryLifeCache.put(164, R.drawable.notification_battery_life_164);
        mBatteryLifeCache.put(165, R.drawable.notification_battery_life_165);
        mBatteryLifeCache.put(166, R.drawable.notification_battery_life_166);
        mBatteryLifeCache.put(167, R.drawable.notification_battery_life_167);
        mBatteryLifeCache.put(168, R.drawable.notification_battery_life_168);
        mBatteryLifeCache.put(169, R.drawable.notification_battery_life_169);
        mBatteryLifeCache.put(170, R.drawable.notification_battery_life_170);
        mBatteryLifeCache.put(171, R.drawable.notification_battery_life_171);
        mBatteryLifeCache.put(172, R.drawable.notification_battery_life_172);
        mBatteryLifeCache.put(173, R.drawable.notification_battery_life_173);
        mBatteryLifeCache.put(174, R.drawable.notification_battery_life_174);
        mBatteryLifeCache.put(175, R.drawable.notification_battery_life_175);
        mBatteryLifeCache.put(176, R.drawable.notification_battery_life_176);
        mBatteryLifeCache.put(177, R.drawable.notification_battery_life_177);
        mBatteryLifeCache.put(178, R.drawable.notification_battery_life_178);
        mBatteryLifeCache.put(179, R.drawable.notification_battery_life_179);
        mBatteryLifeCache.put(180, R.drawable.notification_battery_life_180);
        mBatteryLifeCache.put(181, R.drawable.notification_battery_life_181);
        mBatteryLifeCache.put(182, R.drawable.notification_battery_life_182);
        mBatteryLifeCache.put(183, R.drawable.notification_battery_life_183);
        mBatteryLifeCache.put(184, R.drawable.notification_battery_life_184);
        mBatteryLifeCache.put(185, R.drawable.notification_battery_life_185);
        mBatteryLifeCache.put(186, R.drawable.notification_battery_life_186);
        mBatteryLifeCache.put(187, R.drawable.notification_battery_life_187);
        mBatteryLifeCache.put(188, R.drawable.notification_battery_life_188);
        mBatteryLifeCache.put(189, R.drawable.notification_battery_life_189);
        mBatteryLifeCache.put(190, R.drawable.notification_battery_life_190);
        mBatteryLifeCache.put(191, R.drawable.notification_battery_life_191);
        mBatteryLifeCache.put(192, R.drawable.notification_battery_life_192);
        mBatteryLifeCache.put(193, R.drawable.notification_battery_life_193);
        mBatteryLifeCache.put(194, R.drawable.notification_battery_life_194);
        mBatteryLifeCache.put(195, R.drawable.notification_battery_life_195);
        mBatteryLifeCache.put(196, R.drawable.notification_battery_life_196);
        mBatteryLifeCache.put(197, R.drawable.notification_battery_life_197);
        mBatteryLifeCache.put(198, R.drawable.notification_battery_life_198);
        mBatteryLifeCache.put(199, R.drawable.notification_battery_life_199);
        mBatteryLifeCache.put(200, R.drawable.notification_battery_life_200);
        mBatteryLifeCache.put(201, R.drawable.notification_battery_life_201);
        mBatteryLifeCache.put(202, R.drawable.notification_battery_life_202);
        mBatteryLifeCache.put(203, R.drawable.notification_battery_life_203);
        mBatteryLifeCache.put(204, R.drawable.notification_battery_life_204);
        mBatteryLifeCache.put(205, R.drawable.notification_battery_life_205);
        mBatteryLifeCache.put(206, R.drawable.notification_battery_life_206);
        mBatteryLifeCache.put(207, R.drawable.notification_battery_life_207);
        mBatteryLifeCache.put(208, R.drawable.notification_battery_life_208);
        mBatteryLifeCache.put(209, R.drawable.notification_battery_life_209);
        mBatteryLifeCache.put(210, R.drawable.notification_battery_life_210);
        mBatteryLifeCache.put(211, R.drawable.notification_battery_life_211);
        mBatteryLifeCache.put(212, R.drawable.notification_battery_life_212);
        mBatteryLifeCache.put(213, R.drawable.notification_battery_life_213);
        mBatteryLifeCache.put(214, R.drawable.notification_battery_life_214);
        mBatteryLifeCache.put(215, R.drawable.notification_battery_life_215);
        mBatteryLifeCache.put(216, R.drawable.notification_battery_life_216);
        mBatteryLifeCache.put(217, R.drawable.notification_battery_life_217);
        mBatteryLifeCache.put(218, R.drawable.notification_battery_life_218);
        mBatteryLifeCache.put(219, R.drawable.notification_battery_life_219);
        mBatteryLifeCache.put(220, R.drawable.notification_battery_life_220);
        mBatteryLifeCache.put(221, R.drawable.notification_battery_life_221);
        mBatteryLifeCache.put(222, R.drawable.notification_battery_life_222);
        mBatteryLifeCache.put(223, R.drawable.notification_battery_life_223);
        mBatteryLifeCache.put(224, R.drawable.notification_battery_life_224);
        mBatteryLifeCache.put(225, R.drawable.notification_battery_life_225);
        mBatteryLifeCache.put(226, R.drawable.notification_battery_life_226);
        mBatteryLifeCache.put(227, R.drawable.notification_battery_life_227);
        mBatteryLifeCache.put(228, R.drawable.notification_battery_life_228);
        mBatteryLifeCache.put(229, R.drawable.notification_battery_life_229);
        mBatteryLifeCache.put(230, R.drawable.notification_battery_life_230);
        mBatteryLifeCache.put(231, R.drawable.notification_battery_life_231);
        mBatteryLifeCache.put(232, R.drawable.notification_battery_life_232);
        mBatteryLifeCache.put(233, R.drawable.notification_battery_life_233);
        mBatteryLifeCache.put(234, R.drawable.notification_battery_life_234);
        mBatteryLifeCache.put(235, R.drawable.notification_battery_life_235);
        mBatteryLifeCache.put(236, R.drawable.notification_battery_life_236);
        mBatteryLifeCache.put(237, R.drawable.notification_battery_life_237);
        mBatteryLifeCache.put(238, R.drawable.notification_battery_life_238);
        mBatteryLifeCache.put(239, R.drawable.notification_battery_life_239);
        mBatteryLifeCache.put(240, R.drawable.notification_battery_life_240);
        mBatteryLifeCache.put(241, R.drawable.notification_battery_life_241);
        mBatteryLifeCache.put(242, R.drawable.notification_battery_life_242);
        mBatteryLifeCache.put(243, R.drawable.notification_battery_life_243);
        mBatteryLifeCache.put(244, R.drawable.notification_battery_life_244);
        mBatteryLifeCache.put(245, R.drawable.notification_battery_life_245);
        mBatteryLifeCache.put(246, R.drawable.notification_battery_life_246);
        mBatteryLifeCache.put(247, R.drawable.notification_battery_life_247);
        mBatteryLifeCache.put(248, R.drawable.notification_battery_life_248);
        mBatteryLifeCache.put(249, R.drawable.notification_battery_life_249);
        mBatteryLifeCache.put(250, R.drawable.notification_battery_life_250);
        mBatteryLifeCache.put(251, R.drawable.notification_battery_life_251);
        mBatteryLifeCache.put(252, R.drawable.notification_battery_life_252);
        mBatteryLifeCache.put(253, R.drawable.notification_battery_life_253);
        mBatteryLifeCache.put(254, R.drawable.notification_battery_life_254);
        mBatteryLifeCache.put(255, R.drawable.notification_battery_life_255);
        mBatteryLifeCache.put(256, R.drawable.notification_battery_life_256);
        mBatteryLifeCache.put(257, R.drawable.notification_battery_life_257);
        mBatteryLifeCache.put(258, R.drawable.notification_battery_life_258);
        mBatteryLifeCache.put(259, R.drawable.notification_battery_life_259);
        mBatteryLifeCache.put(260, R.drawable.notification_battery_life_260);
        mBatteryLifeCache.put(261, R.drawable.notification_battery_life_261);
        mBatteryLifeCache.put(262, R.drawable.notification_battery_life_262);
        mBatteryLifeCache.put(263, R.drawable.notification_battery_life_263);
        mBatteryLifeCache.put(264, R.drawable.notification_battery_life_264);
        mBatteryLifeCache.put(265, R.drawable.notification_battery_life_265);
        mBatteryLifeCache.put(266, R.drawable.notification_battery_life_266);
        mBatteryLifeCache.put(267, R.drawable.notification_battery_life_267);
        mBatteryLifeCache.put(268, R.drawable.notification_battery_life_268);
        mBatteryLifeCache.put(269, R.drawable.notification_battery_life_269);
        mBatteryLifeCache.put(270, R.drawable.notification_battery_life_270);
        mBatteryLifeCache.put(271, R.drawable.notification_battery_life_271);
        mBatteryLifeCache.put(272, R.drawable.notification_battery_life_272);
        mBatteryLifeCache.put(273, R.drawable.notification_battery_life_273);
        mBatteryLifeCache.put(274, R.drawable.notification_battery_life_274);
        mBatteryLifeCache.put(275, R.drawable.notification_battery_life_275);
        mBatteryLifeCache.put(276, R.drawable.notification_battery_life_276);
        mBatteryLifeCache.put(277, R.drawable.notification_battery_life_277);
        mBatteryLifeCache.put(278, R.drawable.notification_battery_life_278);
        mBatteryLifeCache.put(279, R.drawable.notification_battery_life_279);
        mBatteryLifeCache.put(280, R.drawable.notification_battery_life_280);
        mBatteryLifeCache.put(281, R.drawable.notification_battery_life_281);
        mBatteryLifeCache.put(282, R.drawable.notification_battery_life_282);
        mBatteryLifeCache.put(283, R.drawable.notification_battery_life_283);
        mBatteryLifeCache.put(284, R.drawable.notification_battery_life_284);
        mBatteryLifeCache.put(285, R.drawable.notification_battery_life_285);
        mBatteryLifeCache.put(286, R.drawable.notification_battery_life_286);
        mBatteryLifeCache.put(287, R.drawable.notification_battery_life_287);
        mBatteryLifeCache.put(288, R.drawable.notification_battery_life_288);
        mBatteryLifeCache.put(289, R.drawable.notification_battery_life_289);
        mBatteryLifeCache.put(290, R.drawable.notification_battery_life_290);
        mBatteryLifeCache.put(291, R.drawable.notification_battery_life_291);
        mBatteryLifeCache.put(292, R.drawable.notification_battery_life_292);
        mBatteryLifeCache.put(293, R.drawable.notification_battery_life_293);
        mBatteryLifeCache.put(294, R.drawable.notification_battery_life_294);
        mBatteryLifeCache.put(295, R.drawable.notification_battery_life_295);
        mBatteryLifeCache.put(296, R.drawable.notification_battery_life_296);
        mBatteryLifeCache.put(297, R.drawable.notification_battery_life_297);
        mBatteryLifeCache.put(298, R.drawable.notification_battery_life_298);
        mBatteryLifeCache.put(299, R.drawable.notification_battery_life_299);


    }

    /**
     * Get the power drawable resource associated with the specified value.
     *
     * @param value the value for which to look up the associated resources.
     * @return the associated power resource.
     */
    public int getPowerResourceForValue(int value) {
        if (value < UIConstants.NOTIFICATION_MIN_POWER)
            value = UIConstants.NOTIFICATION_MIN_POWER;
        Integer resourceId;
        if ((resourceId = mPowerCache.get(value)) == null) {
            resourceId = R.drawable.notification_power_19000;
        }
        return resourceId;
    }

    /**
     * Get the current drawable resource associated with the specified value.
     *
     * @param value the value for which to look up the associated resources.
     * @return the associated current resource.
     */
    public int getCurrentResourceForValue(int value) {
        if (value < UIConstants.NOTIFICATION_MIN_CURRENT)
            value = UIConstants.NOTIFICATION_MIN_CURRENT;
        Integer resourceId;
        if ((resourceId = mCurrentCache.get(value)) == null) {
            resourceId = R.drawable.notification_current_9900;
        }
        return resourceId;
    }

    /**
     * Get the battery life drawable resource associated with the specified value.
     *
     * @param value the value for which to look up the associated resources.
     * @return the associated battery life resource.
     */
    public int getBatteryLifeResourceForValue(int value) {
        if (value < UIConstants.NOTIFICATION_MIN_BATTERY_LIFE)
            value = UIConstants.NOTIFICATION_MIN_BATTERY_LIFE;
        Integer resourceId;
        if ((resourceId = mBatteryLifeCache.get(value)) == null) {
            resourceId = R.drawable.notification_battery_life_299;
        }
        return resourceId;
    }
}
